shinyUI(
  navbarPage("Cloud Seeding", footer="By Christopher Ward",
             tabPanel("Effects on Rainfall",
                      sidebarLayout(
                        sidebarPanel(
                          radioButtons("iVar", 
                                       label = "Choose an independent variable",
                                       choices = c("Seeding",
                                                   "Time",
                                                   "SNE",
                                                   "Cloud Cover",
                                                   "Prewetness",
                                                   "Echo Motion"),
                                       selected = "Seeding"
                          ),
                          hr(),
                          p("We use radio buttons to choose an independent variable against which to compare rainfall."),
                          
                          p("If the app indentifies the chosen variable as a factor with 2 options, it runs a t-test and displays the results.
                              Otherwise, it displays summary statistics."),
                          
                          p("Choose Seeding as the indendent variable, and note that the displayed t-test returns a very high p-value.
                              There is no statistically significant difference in rainfall between the observations with seeding and without seeding.")
                        ),
                        mainPanel(
                          plotOutput("plot1"),
                          pre(textOutput("print1"))
                        )
                      )
             ),
             tabPanel("Multiple Linear Regression",
                      sidebarLayout(
                        sidebarPanel(
                          radioButtons("plotType",
                                       label = "Plot of regression model",
                                       choices = c("Residuals vs Fitted", 
                                                   "Normal Q-Q",
                                                   "Scale-Location", 
                                                   "Cook's distance",
                                                   "Residuals vs Leverage",
                                                   "Cook's dist vs Leverage"
                                       ),
                                       selected = "Residuals vs Fitted"
                          ),
                          hr(),
                          p("We've built a multiple linear regression model, modeling the effects of seeding on rainfall.
                             Along with seeding, we've included cloudcover, prewetness, echomotion, and sne as independent variables."),
                          p("The model was built with the following command:"),
                          pre("lm(rainfall ~ seeding + cloudcover + prewetness + echomotion + sne, data=clouds)"),
                          p("The results of summary() and anova() don't show a strong relationship between rainfall and 
                             any of the independent variables, but there is a weak relationship associated with SNE."),
                          p("Use the radio buttons to explore the various diagnostic plots generated by R.")
                        ),
                        mainPanel(
                          plotOutput("plotLM"),
                          br(),
                          h4("Summary of Model"),
                          pre(textOutput("summaryLM")),
                          br(),
                          h4("ANOVA of Model"),
                          pre(textOutput("anovaLM"))
                        )
                      )
             ),
             tabPanel("Models Comparing Seeding",
                      sidebarLayout(
                        sidebarPanel(
                          radioButtons("sVar", 
                                       label = "Choose a dependent variable",
                                       choices = c("SNE",
                                                   "Cloud Cover",
                                                   "Prewetness"),
                                       selected = "SNE"
                          ),
                          hr(),
                          p("Here we build pairs of models, one using the observations with seeding, one using the observations without seeding."),
                          p("Use the radio buttons to choose an independent variable to examine against rainfall."),
                          p("Choose SNE as the independent variable, and notice the difference of the slopes.
                             The flatter slope for the no-seeding model suggests that rainfall is less dependent on SNE 
                             when seeding is not used.")
                        ),
                        mainPanel(
                          plotOutput("plotS"),
                          hr(),
                          h4("Summary of Seeding SNE Model"),
                          pre(textOutput("summarySeeding")),
                          br(),
                          h4("Summary of No-Seeding SNE Model"),
                          pre(textOutput("summaryNoSeeding"))
                        )
                      )
             )
  )
)